development:
  dialect: "mysql"
  database: "secret_santa_dev"
  host: "127.0.0.1"
  port: "3307"
  user: "root"
  password: "password"

#test:
#  dialect: "mysql"
#  database: "secret-santa-api_test"
#  host: "localhost"
#  port: "3306"
#  user: "root"
#  password: "root"

production:
  url: {{envOr "DATABASE_URL" "mysql://root:password@(127.0.0.1:3307)/secret_santa"}}